# docker/docker-compose.yml

services:
  clab-api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-debian-dind
      args:
        API_USER: ${API_USER_BUILDTIME:-admin}
        API_PASS: ${API_PASS_BUILDTIME:-admin}
    container_name: clab-api-debian-dind
    privileged: true
    restart: unless-stopped
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
      - "${SSH_BASE_PORT:-2222}-${SSH_MAX_PORT:-2322}:${SSH_BASE_PORT:-2222}-${SSH_MAX_PORT:-2322}"
    volumes:
      # Standard volumes only - no bind mounts
      - clab-api-debian-dind-data:/var/lib/docker
      - clab-api-debian-home-data:/home
      - clab-api-debian-config-data:/persistent-config
      # Optional: Mount TLS certificates if TLS_ENABLE=true in .env
      # - ../path/on/host/certs:/certs:ro
    env_file:
      - .env

volumes:
  clab-api-debian-dind-data:
  clab-api-debian-home-data:
  clab-api-debian-config-data: